---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by noneatme.
--- DateTime: 01.12.18 14:51
---


function main(fileName)
    local file = io.open(fileName, "r");
    local number = 0;

    for i in (file:read("*all")):gmatch("%S+") do
        number = number + tonumber(i);
    end

    file:close();
    return number;
end

print(main("2018/1/input.txt"));

--[[
    in Lua 5.1 würde auch folgender Einzeiler gehen:

    return loadfile("2018/1/input.txt");
]]

